### ISSUE TITLE
Device not found on rasberry pi failed to claim usb interface: 0, error: RS2_USB_STATUS_BUSY

### ISSUE THREAD

**Issue by tahir1069** [realsenseai/realsense-ros#2100] opened 2021-10-04 08:59 UTC
I am trying to run a ros instance of relasense ros driver from Rasberyy Pi. But having errors. The driver with all dependencies is installed and the workspace builds without any error. I was able to use that a few months ago but now it fails. 
However I can see the rgb image on rasberry pi ip and the device is also detected in `lsusb`. 
Here is the output of the launch file: 

```bash
... logging to /home/pi/.ros/log/6d309df4-883c-11eb-9f71-dca6327f86e2/roslaunch-raspberrypi-3324.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://raspberrypi:45349/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/confidence_fps: 30
 * /camera/realsense2_camera/confidence_height: 480
 * /camera/realsense2_camera/confidence_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [3335]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 6d309df4-883c-11eb-9f71-dca6327f86e2
process[rosout-1]: started with pid [3348]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [3365]
process[camera/realsense2_camera-3]: started with pid [3366]
[ INFO] [1616107871.142913185]: Initializing nodelet with 4 worker threads.
[ INFO] [1616107871.887233981]: RealSense ROS v2.2.21
[ INFO] [1616107871.887308851]: Built with LibRealSense v2.41.0
[ INFO] [1616107871.887395629]: Running with LibRealSense v2.41.0
[ INFO] [1616107872.006491962]:  
 18/03 23:51:12,052 ERROR [2695877648] (handle-libusb.h:95) failed to claim usb interface: 0, error: RS2_USB_STATUS_BUSY
 18/03 23:51:12,052 ERROR [2731521040] (sensor.cpp:523) acquire_power failed: failed to set power state
 18/03 23:51:12,076 WARNING [2731521040] (rs.cpp:306) null pointer passed for argument "device"
[ WARN] [1616107872.076988481]: Device 1/1 failed with exception: failed to set power state
[ERROR] [1616107872.077624647]: The requested device with  is NOT found. Will Try again.
^C[camera/realsense2_camera-3] killing on exit
[camera/realsense2_camera_manager-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```
I can see that the device is not found. I also run `rs-enumerate-devices` but error is exactly the same. Any thoughts on this issue will be highly appreciated.

**Comment by MartyG-RealSense** [comment] 2021-10-04 09:56
Hi @tahir1069   The problem begins at the point in the log where the details of the attached camera are checked, so it does seem to be a camera non-detection problem, as also strongly suggested by the absence of the camera in **rs-enumerate-devices**.  If the camera was detected in the launch then at the point where the problem begins, it would instead say something like the section of text below.

```
[ INFO] [1632244420.465443424]: Device with physical ID 2-3.4-8 was found.
[ INFO] [1632244420.465521376]: Device with name Intel RealSense D455 was found.
[ INFO] [1632244420.467433152]: Device with port number 2-3.4 was found.
[ INFO] [1632244420.467577472]: Device USB type: 3.2
[ INFO] [1632244420.472245632]: getParameters...
[ INFO] [1632244420.549666912]: setupDevice...
```

Have you changed your librealsense SDK version since the last time that it worked a few months ago?  librealsense version 2.41.0 had some problems that were fixed in 2.42.0.

https://github.com/IntelRealSense/librealsense/pull/8234

Also, are you using the same USB cabling as before?

I also note that you are using ROS Kinetic.  The Kinetic branch was declared 'end of life' by ROS in April 2021, meaning that it receives no further updates.  So I would recommend using Melodic as a minimum if that is possible for your project.  Given that you also experienced camera non-detection in rs-enumerate-devices (a librealsense tool, not a ROS wrapper one), use of Kinetic is likely not the cause of your particular problem in this case.

https://discourse.ros.org/t/preparing-for-final-kinetic-sync/19805

**Comment by MartyG-RealSense** [comment] 2021-10-11 06:00
Hi @tahir1069  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment] 2021-10-17 06:34
Case closed due to no further comments received.

**Closed as completed by MartyG-RealSense** 2021-10-17 06:34 UTC
Labels: question
