### ISSUE TITLE
Auto exposure disabled on D435 while the parameter is set to true on the start.

### ISSUE THREAD

**Issue by deadundead** [realsenseai/realsense-ros#359] opened 2018-04-04 19:20 UTC
The camera starts without auto_exposure enabled, although the parameter is set to true on start. Only works toggling it off and then on in rqt_reconfigure or dynamic_reconfigure package. When starting rqt_reconfigure it also shows the parameter is true from the start. Rosparam get and dynamic get also show that it is true, although it obviously is not enabled on the camera. Check this, please.

**Comment by lorenwel** [comment] 2018-04-09 14:29
Duplicate of #318

**Comment by fiorano10** [comment] 2018-05-09 23:15
@deadundead, did you resolve the issue?

**Comment by fiorano10** [comment] 2018-08-28 03:15
This resolves the issue for now
```
#!/bin/bash
rosrun dynamic_reconfigure dynparam set realsense2_camera_manager rs435_depth_enable_auto_exposure 0
rosrun dynamic_reconfigure dynparam set realsense2_camera_manager rs435_depth_enable_auto_exposure 1
```

**Comment by deadundead** [comment] 2018-08-28 12:21
@fiorano10 , yeah, that's what I actually used, sorry for not replying. But the problem is - if you have all your nodes starting in roslaunch file, you have to open another console to run autoexp toggle script. You can send roslaunch ... to backround though prior to executing dyn_reconf commands, thus losing the ability to correctly stop the whole ROS environment witn Ctrl+C and leaving you only with option of rebooting the whole system. But yeah, this workaround works.

**Comment by doronhi** [comment] 2018-10-11 12:04
I tried it out but can't reproduce.
In base_d400_params.py I changed the default value depth_gain from 16 to 160.
I than run:
`
roslaunch realsense2_camera rs_camera.launch filters:=colorizer
`
rqt_reconfigure shows rs435_depth_gain=160 and rs435_depth_enable_auto_exposure=On.

In a 3rd console I run:
`
rqt_image_view
`
and choose /camera/depth/image_rect_raw

The image looks fine.

Then, in rqt_reconfigure, I choose rs435_depth_enable_auto_exposure=Off and the image turns bad, typical for depth_gain=160.

That means to me that the depth_auto_exposure was indeed On.

Can you reproduce your issue with the current version? Could it be that the issue was already fixed since August?

**Comment by RealSenseCustomerSupport** [comment] 2019-03-07 11:58
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment] 2019-03-20 18:48
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.

**Closed as completed** 2019-03-27 19:07 UTC
