### ISSUE TITLE
Infrared image goes dark randomly

### ISSUE THREAD

**Issue by fiorano10** [realsenseai/realsense-ros#1617] opened 2021-01-08 09:29 UTC
We have a 2 camera setup mounted horizontally to get a  30° overlap. Running librealsense 2.38/2.33, fw 5.12.7.100 on Ubuntu 18.04, kernel version 5.3. The infrared stream randomly goes dark for a couple of frames causing depth issues. It appears that the image goes darker than the lowest exposure setting possible. Is there a way to get exposure value when auto exposure is enabled? Could this caused by turning on the emitter?

![Screenshot from 2021-01-08 04-16-22](https://user-images.githubusercontent.com/10829017/103998334-ec220300-5169-11eb-9abd-4c0a69d467da.png)
![Screenshot from 2021-01-08 04-16-34](https://user-images.githubusercontent.com/10829017/103998342-edebc680-5169-11eb-86e2-54bbda44ac74.png)

**Comment by MartyG-RealSense** [comment] 2021-01-08 11:34
Case closed as a duplicate of https://github.com/IntelRealSense/librealsense/issues/8129

**Closed as completed by MartyG-RealSense** 2021-01-08 11:34 UTC
