### ISSUE TITLE
Auto-Exposure Not Consistently Working at System Init on D435

### ISSUE THREAD

**Issue by dpipemazo** [realsenseai/realsense-ros#318] opened 2018-02-22 23:05 UTC
Running v2.0.2 of this package with v2.10.0 of `librealsense` and camera firmware `5.9.2.0`. Ubuntu 16.04 with 4.10.0-28 kernel.

I noticed quite poor depth performance when viewing the Point Cloud in RVIZ after power cycling the D435 camera but no issue when using `realsense-viewer`. This caused the data in RVIZ to appear splotchy and inconsistent.

I then launched `rosrun rqt_reconfigure rqt_reconfigure` and noticed that the auto-exposure for the depth stream (first checkbox at the top of the `realsense` config menu) was indeed turned on (as indicated by the box being checked). However, unchecking this box and then re-checking it consistently fixed the issue indicating that auto-exposure at nodelet boot is not working. This might be an issue on the `librealsense` side, but I'm not too sure since it looked OK in `realsense-viewer`.

**Comment by Mitchell-Hampton** [comment] 2018-02-23 07:02
I am experiencing the same thing.

**Comment by icarpis** [comment] 2018-02-26 08:17
@Mitchell-Hampton, @dpipemazo, please post the output of the RealSense ROS node.

**Comment by icarpis** [comment] 2018-02-28 07:46
I managed to reproduce this issue and it looks like a firmware bug.
As a workaround you can physically replug the camera or call to [Hardware Reset](https://github.com/IntelRealSense/librealsense/blob/51e766389f75731be6d37a4f435b5c6b172609bc/tools/data-collect/rs-data-collect.cpp#L249) method.

**Comment by dpipemazo** [comment] 2018-02-28 15:52
@icarpis Thanks for looking into it! Sorry I didn't post the output of the node; got pulled away from working on it for a few days. Are you aware of a firmware release schedule or when we might be abe to expect an update?

**Comment by ammarhusain** [comment] 2018-03-10 01:23
I just ran into this issue as well. The auto exposure works well after toggling it off & on in `rqt_reconfigure`. I am going to try calling `hardware_reset` and see if that helps. 

@icarpis I would be really interested in a firmware fix for this as well.

**Comment by agrunnet** [comment] 2018-03-23 14:41
Can you confirm that you are only seeing this on Linux AND ROS? I dont see this issue on Windows, but maybe I am not doing the right thing to reproduce. We need to figure out whether it is FW or SW.

**Comment by reinzor** [comment] 2018-03-29 12:25
We have experienced the same issue, this is the script we use to solve it now (as a workaround):
```
#!/bin/bash
rosrun dynamic_reconfigure dynparam set realsense2_camera_manager rs435_depth_enable_auto_exposure 0
rosrun dynamic_reconfigure dynparam set realsense2_camera_manager rs435_depth_enable_auto_exposure 1
```

This script can be put in the launch file where you start the node and nodelet manager.

**Comment by ammarhusain** [comment] 2018-04-02 16:58
@agrunnet : Yep, I am seeing it only on Linux & ROS. In the Realsense viewer on Windows it launches fine with depth auto exposure enabled.

**Comment by ammarhusain** [comment] 2018-04-19 00:28
Any updates on this issue?

**Comment by fiorano10** [comment] 2018-05-09 23:14
@reinzor, I'm on the latest version for the librealense, SDK, and so on. Your script doesn't seem to work, I still have to toggle it in rqt_reconfigure. Any suggestions?

**Comment by reinzor** [comment] 2018-05-10 07:04
@fiorano10 , this script performs exactly the same service calls than you are doing with the gui. Please check whether your node argument is correct:
```
Usage: dynparam set [options] node parameter value
```

**Comment by fiorano10** [comment] 2018-05-11 16:22
It's working, thanks! I had the incorrect value for parameter

**Comment by reinzor** [comment] 2018-06-01 18:32
Yes, re-check your nodelet manager name. The first argument (args attribute) has to point to the nodelet manager that is running your camera driver nodelet.

You can use the `rosnode` cli to obtain the names of the running nodes:
```
rosnode list
```

maybe adding the `/camera/` prefix will already solve your problem

**Comment by ZacharyTaylor** [comment] 2018-06-05 09:16
I have had the same issue with the d415. I believe it is caused as setting the manual exposure causes the system to drop out of auto exposure mode, and the manual exposure is set on startup.

I fixed the issue on my system by adding

`if(config.rs415_depth_enable_auto_exposure){
    BaseD400Node::setParam(config, base_depth_enable_auto_exposure);
}`

After this line https://github.com/intel-ros/realsense/blob/development/realsense2_camera/src/rs415_node.cpp#L93. I expect the same fix would work for the d435 node

**Comment by remod** [comment] 2018-06-07 09:14
Thanks @ZacharyTaylor ! I can confirm it works for the d435.

**Comment by lorenwel** [comment] 2018-06-07 09:38
Thanks @ZacharyTaylor. I opened PR #392 implementing the proposed fix.

**Comment by alspitz** [comment] 2018-07-16 03:13
Hope to see this fixed soon!

**Comment by Metalzero2** [comment] 2018-09-05 07:58
Running the procedure that @dpipemazo mentioned in his original post, with the latest RealSense updates (that is librealsense version 2.16, Real Sense firmware version 05.10.03 and latest realsense2_camera [31a0e4d] ), it would seem that auto exposure is working on start up.

It would be interesting if others could conform this as well.

**Comment by doronhi** [comment] 2018-10-29 14:35
fixed in the latest commit. Will be available in the upcoming release, hopefully by tomorrow.

**Closed as completed by doronhi** 2018-10-29 14:35 UTC
Labels: bug, ROS Wrapper 2, firmware
