### ISSUE TITLE
Pipeline syncer is not included in 2.19 version and is creating issue during build.

### ISSUE THREAD

**Issue by brolinA** [realsenseai/realsense-ros#705] opened 2019-03-28 09:12 UTC
The issue is not fixed in the updated version i.e, 2.19.0. So I have to manually place the lines from this [merge request](https://github.com/intel-ros/realsense/pull/452/files) to make my code work

**Comment by doronhi** [comment] 2019-03-28 14:15
I'm not sure what the issue is? The PR is merged in realsense2_wrapper.
Could you please elaborate?

**Comment by RealSenseCustomerSupport** [comment] 2019-07-26 03:14
----------------------------------------------

@Brolin56 As dorohni replied the PR is already merged. Could you please double check? Thanks!

**Comment by RealSenseCustomerSupport** [comment] 2019-08-07 05:11
----------------------------------------------

@Brolin56 Sorry that we didn't get reply from you for weeks. Will close the issue accordingly. Please feel free to create another one if you still have issues/questions. Thanks!

**Closed as completed** 2019-08-07 06:02 UTC
