### ISSUE TITLE
 /camera/depth_registered/points err point cloud distance

### ISSUE THREAD

**Issue by woshisj** [realsenseai/realsense-ros#553] opened 2018-12-22 04:55 UTC
### when I run the command
`$ roslaunch realsense_ros_camera rs_rgbd.launch align_depth:=true
`
### and I measure the distance is 1.332m
![image](https://user-images.githubusercontent.com/32431758/50370786-21417400-05e8-11e9-9c6c-3d265ec81099.png)
### in face the last result correct
![image](https://user-images.githubusercontent.com/32431758/50370818-97de7180-05e8-11e9-955c-bad2d17db82d.png)

### Is there anything I need to set?

Running with LibRealSense v2.17.0
RealSense ROS v2.1.2
Device FW version: 3.21.0.0

**Comment by ghost** [comment] 2018-12-27 20:39
I also have the same issue and the details can be found [here](https://answers.ros.org/question/311478/point-cloud-data-appears-larger-than-it-should-be-in-rviz/).

**Comment by doronhi** [comment] 2019-01-27 14:40
Hi @woshisj,
Sorry for the long delay. 
Can you confirm that the problem still exists with the latest release (2.1.4(ROS) and 2.18.0)?
I tried but could not reproduce.
I get the same correct measures on topic "/camera/depth_registered/points" when I run:
`roslaunch realsense2_camera rs_rgbd.launch align_depth:=true`

as when I run 
`roslaunch realsense2_camera rs_camera.launch filters:=pointcloud align_depth:=true`
which is what I assume you used for getting the topic "/camera/depth/color/points"

**Comment by RealSenseCustomerSupport** [comment] 2019-03-07 12:20
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment] 2019-04-04 08:59
----------------------------------------------

@woshisj Did you get chance to try the latest release(2.2.2(ROS) and 2.19.2) to see if the issue still existing? Looking forward to your update. Thanks!

**Comment by RealSenseCustomerSupport** [comment] 2019-04-08 03:04
----------------------------------------------

@woshisj Any update? Thanks!

**Comment by woshisj** [comment] 2019-04-09 06:51
> @woshisj Any update? Thanks!

sorry， I have not used SR300 recently.
I will update it the next time I use it.

**Comment by RealSenseCustomerSupport** [comment] 2019-04-26 03:39
----------------------------------------------

@woshisj Ok. If no other questions about the ticket, will close it accordingly. Please feel free to open new ticket if you still get the issue when use SR300 next time. Thanks!

**Closed as completed** 2019-05-03 04:06 UTC
