### ISSUE TITLE
problem on application

### ISSUE THREAD

**Issue by bladesaber** [realsenseai/realsense-ros#1572] opened 2020-12-16 12:05 UTC
Dear anyone:
    I am doing a project about use D435 camera in indoor at night time, because of the demand of customer, there is no light in the environment, so I decide to  use IR image. But I find some problems and hoping help:
(1) when I get image from left or right camera, there is a lot of light spots which cause by laser emitter, how can I remove them
(2) I try to set rs.option.laser_power to low value which can remove the light spot, but it seems that it will affect the quality  of depth image, so I think may be it is not a good idea, do you have some better ideas?
(3) can I use external IR Illuminator, if I use other external IR Illuminator, does it be help to remove light spot or it will do harm to depth image?

**Comment by MartyG-RealSense** [comment] 2020-12-16 13:07
Closed as duplicate of https://github.com/IntelRealSense/librealsense/issues/8015

**Closed as completed by MartyG-RealSense** 2020-12-16 13:07 UTC
