### ISSUE TITLE
Calibration of D415 in ROS

### ISSUE THREAD

**Issue by shrijan00** [realsenseai/realsense-ros#508] opened 2018-11-03 08:23 UTC
Hi,
I'm trying to calibrate realsense in a similar fashion as i did for Kinect in ROS using a checkerboard.
For RGB----->rosrun camera_calibration cameracalibrator.py image:=/camera/color/image_raw camera:=/camera/color --size 8x6 --square 0.0245
For Depth-->rosrun camera_calibration cameracalibrator.py image:=/camera/color/image_rect_raw camera:=/camera/depth --size 8x6 --square 0.0245
But everytime i get the error service not found. 
 But when i did for kinect it saved .yaml file automatically in .ros folder. I already did the dynamic calibration as mentioned on Intel website. But that calibration file i guess i cannot use .yaml file in ros. So, i was trying to get the same .yaml file for d415 in ROS. Please help.

**Comment by doronhi** [comment] 2018-11-07 07:44
Hi,
Duplicate of: https://github.com/IntelRealSense/librealsense/issues/2666
I am not sure exactly what you are trying to achieve.

The output of the calibration process is set in the firmware and so, no file is needed for the operation of realsense2_camera ROS wrapper or other realsense based applications. That's why there is no file.

I am not familiar with the camera_calibration application. If you need to obtain the values of the calibration to create your own .yaml file you can get the current values by typing:
`rs-enumerate-devices -c`

**Closed as completed** 2018-11-07 08:42 UTC

**Comment by ashirsat** [comment] 2019-11-24 23:05
@doronhi is there a way to get the intrinsic and the distrortion vector for the camera. These if obtained can be helpful in getting relasense cameras to work wiith other opencv applications like aruco-tags

**Comment by TheVetter** [comment] 2020-02-03 17:56
Yes I am have the question as well.

how do i get the information needed for this https://berndpfrommer.github.io/tagslam_web/intrinsic_calibration/

**Comment by doronhi** [comment] 2020-02-04 04:59
Could you elaborate? Why is `rs-enumerate-devices -c` not working for you?

**Comment by TheVetter** [comment] 2020-02-05 23:18
it did i got it to work. I was just being stupid.
