### ISSUE TITLE
Question regarding high quality depth image and infra without dots

### ISSUE THREAD

**Issue by Kaijun101** [realsenseai/realsense-ros#2307] opened 2022-04-01 07:03 UTC
Hi @MartyG-RealSense, can I check with you if its possible to enable to emitter to on and off so that it can generate high quality depth image while not having infra emitter on for the infra stream?

**Comment by MartyG-RealSense** [comment] 2022-04-01 07:12
Hi @Kaijun101  Emitter on-off will continuously alternate the emitter on and off.  If you wish to completely turn off the emitter then you can either set the Laser Power option to '0' with **RS2_OPTION_LASER_POWER** or disable the emitter with **RS2_OPTION_EMITTER_ENABLED**

The link below provides example C++ code under the **librealsense2** heading for controlling the laser power and emitter on / off status.  If you require Python code for doing so, please let me know.

https://dev.intelrealsense.com/docs/api-how-to#section-controlling-the-laser

**Edit:** As this is a RealSense ROS case, you want to know how to control it in ROS, yes?

**Comment by Kaijun101** [comment] 2022-04-01 07:52
Yes, I would like to know how to control it in ROS. Like how can I off the emitter when publishing infra image and enable it when publishing depth image. So that, I can achieve both high quality depth image and infra without the emitter dots.

**Comment by MartyG-RealSense** [comment] 2022-04-01 08:23
If your scene is well lit then a 400 Series camera can alternatively use the ambient light in a scene to analyze surfaces for depth detail instead of having the IR dot pattern projection enabled.

If you are using ROS1 (Kinetic, Melodic, Noetic), a RealSense ROS user shares their launch file instructions in https://github.com/IntelRealSense/realsense-ros/issues/1379#issuecomment-934502369 for disabling the emitter with a rosparam command.

```
<rosparam> 
/camera/stereo_module/emitter_enabled: 2
</rosparam>
```

Again for ROS1, https://github.com/IntelRealSense/realsense-ros/issues/1379 provides an example of controlling the laser power and emitter on / off status during runtime after launch with dynamic reconfigure.

**Comment by Kaijun101** [comment] 2022-04-06 17:13
Hi @MartyG-RealSense, I notice that on my realsense-ros it state it was bulit with librealsense v2.50.0, also I checkout realsense-ros to 2.3.0. But on my com, I built only v2.4.50 and when I run realsense-viewer, it shows as v2.45.0. Can u assist me on this?

**Comment by MartyG-RealSense** [comment] 2022-04-06 18:10
If the log states that it was built with 2.50.0 but running with 2.45.0, that would indicate that originally librealsense 2.50.0 was installed at the time that the ROS wrapper was built but then the librealsense version was changed to 2.45.0 at some time **after** the ROS wrapper was built.

Whenever the librealsense version is changed, the ROS wrapper must be built again or the different built with / running with version numbers occur.

**Comment by Kaijun101** [comment] 2022-04-07 04:23
I have uninstall both and reinstall but it still state as built with v2.50.0. Can u advise me on how to resolve this or is there any recommended steps to do so?

**Comment by MartyG-RealSense** [comment] 2022-04-07 07:48
Do you mean that the log still says 'built with 2.50.0, running with 2.45.0' ?

**Comment by Kaijun101** [comment] 2022-04-07 08:24
Yes, it says built with 2.50.0

**Comment by MartyG-RealSense** [comment] 2022-04-07 08:33
If you built the ROS wrapper with **git checkout `git tag | sort -V | grep -P "^2.\d+\.\d+" | tail -1`** then the latest ROS wrapper version will be installed.  For ROS1 that is **2.3.2** for use with SDK 2.50.0.

If you wanted to use librealsense 2.45.0 then wrapper **2.3.0** should be used.

 I see that you previously used the command below a couple of months ago to install librealsense 2.45.0 at https://githubhot.com/repo/engcang/vins-application/issues/9

**git checkout v2.45.0**

If you want to install ROS wrapper 2.3.2 then use the default git checkout tag instruction.  For wrapper 2.3.0 for use with SDK 2.45.0, try **git checkout v2.3.0** instead.

**Comment by Kaijun101** [comment] 2022-04-07 09:39
Thanks for your advice. I managed to resolve this issue. But now when I run the ros-wrapper it shows my d435i as connected to usb 2.1 even though I am using a usb3 port.

**Comment by MartyG-RealSense** [comment] 2022-04-07 09:42
It's excellent to hear that you made progress.

Does the USB still show as 2.1 in the log if you add a camera reset instruction to your roslaunch to reset the camera at launch?

**roslaunch realsense2_camera rs_camera.launch initial_reset:=true**

**Comment by Kaijun101** [comment] 2022-04-07 10:00
Yes the issue presists. I tried the same wire with another d435i i got usb3.2. I also got this error: [ WARN] [1649325680.195874727]: Hardware Notification:Motion Module failure,1.64933e+12,Error,Hardware Error

**Comment by MartyG-RealSense** [comment] 2022-04-07 11:02
Does the Motion Module Failure error occur on the camera detected as USB 2.1 or on the other camera that you tried?

Which camera firmware driver version are you using with the cameras, please?

**Comment by Kaijun101** [comment] 2022-04-07 14:44
The error occurs on the camera detected as usb 2.1. I tried both 5.13.0.50 and 5.12.14.50 but both also detect as usb 2.1

**Comment by MartyG-RealSense** [comment] 2022-04-07 16:29
So the USB cable is okay as your other D435i camera was detected as USB 3.2 when using it with that camera.

Have you tried unplugging the micro end of the USB cable from the side of the camera, turning it around the other way and re-inserting it (as USB-C cables are two-way insertion on the micro sized end).  Whilst doing this reversal usually only makes a difference on the L515 camera model, it is worth trying in order to confirm or eliminate it as a possible solution.

**Comment by Kaijun101** [comment] 2022-04-08 08:28
Yes, I have tried inserting it both ways and it still detect as usb 2.1. Not sure what's wrong with the D435i, but the cable is ok as the other camera is detected as usb 3.2. I changed another cable and its also usb 2.1.

**Comment by MartyG-RealSense** [comment] 2022-04-08 08:49
Does the affected camera have 2.1 beside its name in the options side-panel of the Viewer, or is it only the ROS wrapper that the USB mis-detection is occurring in?

![image](https://user-images.githubusercontent.com/41145062/162400706-a0a0bf97-39e1-43c3-95b4-f4bccf2e7fd9.png)

**Comment by Kaijun101** [comment] 2022-04-08 12:52
Yes, realsense-viewer also shows usb2.1.

**Comment by MartyG-RealSense** [comment] 2022-04-08 13:44
Is the camera still detected as USB 2.1 if you reset the camera to its factory-new configuration in the Viewer using the instructions at https://github.com/IntelRealSense/librealsense/issues/10182#issuecomment-1019854487

**Comment by Kaijun101** [comment] 2022-04-09 07:07
Yes, the camera is still detected as USB 2.1.

**Comment by MartyG-RealSense** [comment] 2022-04-09 09:01
Having looked at all the information in this case, there seems to be a high probability that the problem is with the particular computer rather than the camera hardware.  Sometimes a particular camera may stop working correctly on a certain PC whilst other cameras work normally, whilst the affected camera works correctly when tried on a different computer.  

I have a D435i that exhibits this behaviour (works fine on one Windows laptop but does not detect correctly on another Windows laptop, whilst other cameras work normally on the affected laptop).  As this is apparently a Windows related issue, a solution has not yet been found.  

Are you using Windows or Ubuntu, please?

**Comment by Kaijun101** [comment] 2022-04-10 05:45
I am currently using ubuntu 18.04.

**Comment by MartyG-RealSense** [comment] 2022-04-10 09:55
Thanks for the confirmation of your OS.  Is it still detected as 2.1 if you reload the Ubuntu **udev rules**

`sudo cp ~/.99-realsense-libusb.rules /etc/udev/rules.d/99-realsense-libusb.rules && sudo udevadm control --reload-rules && udevadm trigger`

**Comment by Kaijun101** [comment] 2022-04-11 15:26
Yes, it still detected as usb2.1. The fiollowing errors appears as well I noticed.

 11/04 23:25:35,846 ERROR [547406999328] (error-handling.cpp:78) Error during polling error handler: usb device disconnected
 11/04 23:25:36,847 ERROR [547113385760] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_NO_DEVICE
 11/04 23:25:36,847 ERROR [547406999328] (sensor.cpp:526) acquire_power failed: failed to set power state
 11/04 23:25:36,847 ERROR [547406999328] (error-handling.cpp:78) Error during polling error handler: failed to set power state
 11/04 23:25:37,848 ERROR [547113385760] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_NO_DEVICE
 11/04 23:25:37,848 ERROR [547406999328] (sensor.cpp:526) acquire_power failed: failed to set power state
 11/04 23:25:37,849 ERROR [547406999328] (error-handling.cpp:78) Error during polling error handler: failed to set power state
 11/04 23:25:38,849 ERROR [547113385760] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_NO_DEVICE
 11/04 23:25:38,849 ERROR [547406999328] (sensor.cpp:526) acquire_power failed: failed to set power state
 11/04 23:25:38,849 ERROR [547406999328] (error-handling.cpp:78) Error during polling error handler: failed to set power state

**Comment by MartyG-RealSense** [comment] 2022-04-11 15:51
Are you using two D435i at the same time or just one at a time, please?

**Comment by Kaijun101** [comment] 2022-04-12 07:18
1 at ta time

**Comment by MartyG-RealSense** [comment] 2022-04-12 10:26
Which firmware version is the other D435i that works normally using?

**Comment by MartyG-RealSense** [comment] 2022-04-18 06:21
Hi @Kaijun101  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment] 2022-04-24 06:23
Case closed due to no further comments received.

**Closed as completed by MartyG-RealSense** 2022-04-24 06:23 UTC
Labels: question
