### ISSUE TITLE
Aligned Depth to Color Image not being published

### ISSUE THREAD

**Issue by hello-jackson** [realsenseai/realsense-ros#2797] opened 2023-06-29 23:41 UTC
Hey team,

I am using a D435i camera with LibRealSense v2.54.1 and Device FW version: 5.15.0.2 with ROS 2 Galactic and the realsense-ros package built from source with RealSense ROS v4.54.1. 

When I launch the camera with the parameter align_depth.enable=true, the RGB feed on /camera/color/image_raw feed starts to flicker and the topic /camera/aligned_depth_to_color topic is not published. This worked for me until recently, and the same setup for the firmware and SDK works in ROS Noetic. Has something changed in the ROS 2 driver that causes the aligned_depth_to_color topic to fail?

Thank you,
Chintan Desai

**Comment by hello-chintan** [comment] 2023-06-29 23:46
Oops. I'll be following up with this account. Please tag me when you reply.

Chintan Desai

**Comment by MartyG-RealSense** [comment] 2023-06-30 10:30
Hi @hello-chintan  There have not been any other reports yet of the problem that you described occurring with ROS wrapper 4.54.1.

Does the problem still occur if you launch with **ros2 run** instead of ros2 launch ?

`ros2 run realsense2_camera realsense2_camera_node --ros-args -p align_depth.enable:=true`

**Comment by hello-chintan** [comment] 2023-06-30 17:30
Hey @MartyG-RealSense, yes, I can confirm that this happens with the `ros2 run realsense2_camera realsense2_camera_node --ros-args -p align_depth.enable:=true` command as well. The issue is reproducible while working on ROS 2 Humble as well with the most recent realsense_ros drivers built from source in my workspace.

**Comment by MartyG-RealSense** [comment] 2023-07-01 09:04
I have highlighted this issue to my Intel RealSense colleagues on the ROS team to discuss it with them.  Thanks very much for your patience.

**Comment by hello-chintan** [comment] 2023-07-03 16:49
Glad that the bug was found. Thanks for working on it, @MartyG-RealSense!

**Comment by MartyG-RealSense** [comment] 2023-07-03 16:53
You are very welcome, @hello-chintan  - I'm pleased that my colleagues implemented a fix for your issue!

**Comment by hello-chintan** [comment] 2023-07-04 00:01
The issue is fixed. Closing this issue. Thanks again!

**Comment by hello-chintan** [comment] 2023-07-04 00:02
I can confirm, the issue is now resolved with the new updates. Thanks again!

**Comment by MartyG-RealSense** [comment] 2023-07-04 06:48
As your issue is resolved, I will close it.  Thanks for the confirmation!

**Closed as completed by MartyG-RealSense** 2023-07-04 06:48 UTC
Labels: D400
