### ISSUE TITLE
Setting frame queue size

### ISSUE THREAD

**Issue by Serafadam** [realsenseai/realsense-ros#937] opened 2019-09-30 14:45 UTC
Hey, I want to follow up [this issue](https://github.com/IntelRealSense/librealsense/issues/4955#issue-500247500) on the main realsense repository. My question for now is, is there an easy way to set the frame queue capacity via the ROS interface?

**Comment by doronhi** [comment] 2019-10-06 07:47
As opposed to the latency tool, realsense2_camera does not use pipeline but callbacks where getting frames from librealsense. Therefor there is no "queue capacity" to control.

**Comment by Serafadam** [comment] 2019-10-06 13:36
So this means that the latency isn't tied to the fps?

**Comment by RealSenseCustomerSupport** [comment] 2020-02-05 07:07
----------------------------------------------

@Brudasoe Seen from the testing result, the latency by latency-tool below should be something related to the fps.
https://github.com/IntelRealSense/librealsense/tree/master/wrappers/opencv/latency-tool

**Comment by RealSenseCustomerSupport** [comment] 2020-02-11 01:00
----------------------------------------------

@Brudasoe Any other questions about this ticket? Looking forward to your update. Thanks!

**Comment by Serafadam** [comment] 2020-02-13 14:19
Thanks for following up on that, I did some tests, and it seems that latency did improve with more fps, even though I didn't check that thoroughly.

 I had a problem that I had calibrated the position of the camera with respect to the robot arm (hand-eye calibration), and after that I wanted to do a scanning motion, and it seemed like the camera was a little lagging with what I had expected, and that caused some issues, more with slower fps. 
I guess a way to solve that would be to synchronize internal Realsense clock with other clocks (for example with one on robot). But it's a little hard to do that programmatically without modifying the camera's internal code.

**Comment by RealSenseCustomerSupport** [comment] 2020-02-14 03:08
----------------------------------------------

@Brudasoe Please check below document to see if you can apply HW sync between the camera and  the robot.
https://dev.intelrealsense.com/docs/multiple-depth-cameras-configuration

**Comment by doronhi** [comment] 2020-02-16 07:57
The timestamp marked with "Global Timestamp domain" is synchronized to the host clock.
You could synchronize the host clock with the robot's clock (or if they are the same, the problem is solved).

**Comment by RealSenseCustomerSupport** [comment] 2020-02-27 00:40
----------------------------------------------

@Brudasoe Any other questions about this? Thanks!

**Comment by Serafadam** [comment] 2020-03-04 10:08
No, thanks, I am good for now :slightly_smiling_face:

**Comment by RealSenseCustomerSupport** [comment] 2020-03-09 01:00
----------------------------------------------

@Brudasoe Glad to hear that. Close this accordingly. Thanks!

**Closed as completed** 2020-03-09 01:04 UTC
