### ISSUE TITLE
Realsense2 with L515 unable to view any streams

### ISSUE THREAD

**Issue by ghost** [realsenseai/realsense-ros#2107] opened 2021-10-09 15:59 UTC
I have a realsense l515 that I am trying to use in ROS2 (foxy). I am able to use my camera normally in realsense-viewer and see the depth and image data with no issue.
When I run the rs_launch.py file, I am unable to view any data in rviz. I have set the fixed frame correctly but I cannot even view the 2D color or image data. When I launch the file with the parameter "filter:=pointcloud", the point cloud topic is created and I can echo the pointcloud topic and see taht data is being published but it is not viewable in rviz. The same issue persists when I try launching the demo_pointcloud_launch.py demo. I have tried lowering the fps and disabling the infra stream to just see the depth and color with no success. I have attached console logs of both me running the pointcloud demo and a log of the pointcloud topic.
console from launch
`
[INFO] [launch]: All log files can be found below /home/group14/.ros/log/2021-10-09-12-44-26-794696-group14-68102
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [realsense2_camera_node-1]: process started with pid [68104]
[INFO] [rviz2-2]: process started with pid [68106]
[realsense2_camera_node-1] [0m[INFO] [1633794267.020621591] [RealSenseCameraNode]: RealSense ROS v3.2.2[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.020674050] [RealSenseCameraNode]: Built with LibRealSense v2.48.0[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.020683287] [RealSenseCameraNode]: Running with LibRealSense v2.48.0[0m
[realsense2_camera_node-1]  09/10 12:44:27,129 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
[realsense2_camera_node-1] [0m[INFO] [1633794267.222955647] [RealSenseCameraNode]: Device with serial number f0271990 was found.
[realsense2_camera_node-1] [0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.222980546] [RealSenseCameraNode]: Device with physical ID 2-1-8 was found.[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.222985988] [RealSenseCameraNode]: Device with name Intel RealSense L515 was found.[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.223283864] [RealSenseCameraNode]: Device with port number 2-1 was found.[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.223299400] [RealSenseCameraNode]: Device USB type: 3.2[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.224880141] [RealSenseCameraNode]: getParameters...[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.227040826] [RealSenseCameraNode]: setupDevice...[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.227066731] [RealSenseCameraNode]: JSON file is not provided[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.227082456] [RealSenseCameraNode]: Device Name: Intel RealSense L515[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.227091757] [RealSenseCameraNode]: Device Serial No: f0271990[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.227100256] [RealSenseCameraNode]: Device physical port: 2-1-8[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.227108131] [RealSenseCameraNode]: Device FW version: 01.05.08.01[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.227116064] [RealSenseCameraNode]: Device Product ID: 0x0B64[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.227123627] [RealSenseCameraNode]: Enable PointCloud: On[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.227131141] [RealSenseCameraNode]: Align Depth: Off[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.227138674] [RealSenseCameraNode]: Sync Mode: On[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.227160318] [RealSenseCameraNode]: Device Sensors: [0m
[rviz2-2] [INFO] [1633794267.240073303] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1633794267.240274091] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[realsense2_camera_node-1] [0m[INFO] [1633794267.242198489] [RealSenseCameraNode]: L500 Depth Sensor was found.[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.249633427] [RealSenseCameraNode]: RGB Camera was found.[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.249808784] [RealSenseCameraNode]: Motion Module was found.[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.249837733] [RealSenseCameraNode]: (Infrared, 1) sensor isn't supported by current device! -- Skipping...[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.249850620] [RealSenseCameraNode]: (Infrared, 2) sensor isn't supported by current device! -- Skipping...[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.249861769] [RealSenseCameraNode]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.249872174] [RealSenseCameraNode]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.249882320] [RealSenseCameraNode]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.249899629] [RealSenseCameraNode]: (Pose, 0) sensor isn't supported by current device! -- Skipping...[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.249912587] [RealSenseCameraNode]: Add Filter: pointcloud[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.250494611] [RealSenseCameraNode]: num_filters: 1[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.250513150] [RealSenseCameraNode]: Setting Dynamic reconfig parameters.[0m
[rviz2-2] [INFO] [1633794267.274800260] [rviz2]: Stereo is NOT SUPPORTED
[realsense2_camera_node-1] [33m[WARN] [1633794267.426957036] [RealSenseCameraNode]: Could not set param: pointcloud.stream_index_filter with 0Range: [-1, -2147483648]: parameter 'pointcloud.stream_index_filter' could not be set: Parameter {} doesn't comply with integer range.[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.427008218] [RealSenseCameraNode]: Done Setting Dynamic reconfig parameters.[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.427463629] [RealSenseCameraNode]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.427746336] [RealSenseCameraNode]: infra stream is enabled - width: 640, height: 480, fps: 30, Format: Y8[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.429618536] [RealSenseCameraNode]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.429717321] [RealSenseCameraNode]: setupPublishers...[0m
[realsense2_camera_node-1] [0m[INFO] [1633794267.434259141] [RealSenseCameraNode]: setupStreams...[0m
[rviz2-2] [INFO] [1633794267.446737932] [rviz2]: Stereo is NOT SUPPORTED
[realsense2_camera_node-1]  09/10 12:44:27,445 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
[realsense2_camera_node-1]  09/10 12:44:27,540 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[realsense2_camera_node-1] [0m[INFO] [1633794267.557363900] [RealSenseCameraNode]: SELECTED BASE:Depth, 0[0m
[realsense2_camera_node-1]  09/10 12:44:27,590 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[realsense2_camera_node-1]  09/10 12:44:27,641 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[realsense2_camera_node-1]  09/10 12:44:27,692 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[realsense2_camera_node-1] [0m[INFO] [1633794267.742718609] [RealSenseCameraNode]: RealSense Node Is Up![0m
[realsense2_camera_node-1] [33m[WARN] [1633794267.747024564] [RealSenseCameraNode]: [0m
[realsense2_camera_node-1] [33m[WARN] [1633794267.747077428] [RealSenseCameraNode]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.[0m
[realsense2_camera_node-1]  09/10 12:44:28,246 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[realsense2_camera_node-1]  09/10 12:44:28,592 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[realsense2_camera_node-1] [0m[INFO] [1633794269.047879850] [RealSenseCameraNode]: publishing unordered pointcloud.[0m
[realsense2_camera_node-1]  09/10 12:44:29,844 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[realsense2_camera_node-1]  09/10 12:44:31,095 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[realsense2_camera_node-1]  09/10 12:44:32,346 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[realsense2_camera_node-1]  09/10 12:44:33,597 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[realsense2_camera_node-1]  09/10 12:44:34,849 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[realsense2_camera_node-1]  09/10 12:44:36,100 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[INFO] [rviz2-2]: process has finished cleanly [pid 68106]
[realsense2_camera_node-1]  09/10 12:44:37,352 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[realsense2_camera_node-1]  09/10 12:44:38,603 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[realsense2_camera_node-1]  09/10 12:44:39,855 WARNING [140508059899648] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[realsense2_camera_node-1] [0m[INFO] [1633794280.119950337] [rclcpp]: signal_handler(signal_value=2)[0m
[INFO] [realsense2_camera_node-1]: process has finished cleanly [pid 68104]
`
pointcloud topic
`
header:
  stamp:
    sec: 1633794404
    nanosec: 869805013
  frame_id: camera_depth_optical_frame
height: 1
width: 99226
fields:
- name: x
  offset: 0
  datatype: 7
  count: 1
- name: y
  offset: 4
  datatype: 7
  count: 1
- name: z
  offset: 8
  datatype: 7
  count: 1
- name: rgb
  offset: 16
  datatype: 7
  count: 1
is_bigendian: false
point_step: 20
row_step: 1984520
data:
- 131
- 154
- 237
- 191
- 114
- 13
- 168
- 191
- 173
- 28
- 66
- 64
- 0
- 0
- 0
- 0
- 44
- 65
- 61
- 0
- 40
- 15
- 198
- 191
- 55
- 129
- 135
- 191
- 224
- 79
- 29
- 64
- 0
- 0
- 0
- 0
- 56
- 77
- 73
- 0
- 105
- 114
- 179
- 191
- 163
- 181
- 146
- 191
- 236
- 81
- 42
- 64
- 0
- 0
- 0
- 0
- 53
- 79
- 67
- 0
- 213
- 179
- 178
- 191
- 163
- 181
- 146
- 191
- 236
- 81
- 42
- 64
- 0
- 0
- 0
- 0
- 57
- 80
- 70
- 0
- 63
- 245
- 177
- 191
- 163
- 181
- 146
- 191
- 236
- 81
- 42
- 64
- 0
- 0
- 0
- 0
- 58
- 76
- 73
- 0
- 197
- 32
- 164
- 191
- 171
- 3
- 145
- 191
- 29
- 90
- 40
- 64
- 0
- 0
- 0
- 0
- 52
- 77
- 62
- 0
- 107
- 96
- 163
- 191
- 37
- 0
- 145
- 191
- '...'
is_dense: true
`

**Comment by MartyG-RealSense** [comment] 2021-10-09 16:25
Hi @seandburke99  Could you provide a response to the questions below, please?

1.  What computer or computing device are you using (PC, Raspberry Pi, Nvidia Jetson, etc)

2.  Does performance improve if you unplug the micro-sized end of the USB cable from the base of the L515 camera, turn the corrector around to the opposite orientation and re-insert the connector into the camera (USB Type-C cables are two-way insertion at the micro-sized end).

3.  If reversing the USB connector does not help, do you see improvement if you add an **initial_reset:=true** command to your launch instruction to reset the camera at launch.

**Comment by ghost** [comment] 2021-10-12 13:37
Hello,
1. PC. Ubuntu 20.
2. No change.
3. I have tried initial_reset:=true on but it did not change anything.

**Comment by MartyG-RealSense** [comment] 2021-10-12 16:18
The high number of occurrences of the **control_transfer returned** warning is the most likely candidate at present for the cause of the data not being displayed in RViz.  If you are receiving the warning only a small number of times during launch and then they stop, or they occur one or two times a minute after launch, then this warning can be safely ignored.  If this warning is generating continuously though then it can indicate a serious communication problem with the device.

When reducing the resolution, did you provide three factors (width, height and FPS) for each stream type in the roslaunch instruction, please?  If these three factors are not provided in the custom configuration then the lauch deems the custom configuration invalid and applies the default configuration of the particular camera model instead.  An example of a ROS2 depth-only launch configuration suited to an L515 is provided below.

**ros2 launch realsense2_camera rs_launch.py depth_width:=640 depth_height:=480 depth_fps:=30.0**

If a low-resolution depth-only configuration such as this still results in control_transfer returned warnings then it would suggest that the problem is not related to too much data being recevied by the USB port.

**Comment by ghost** [comment] 2021-10-13 12:34
I will give that a try. I am confused how this communication problem would arise if the realsense viewer does not seem to have an issue retrieving an image, would they not be fundamentally the same operations?

**Comment by MartyG-RealSense** [comment] 2021-10-13 12:37
There are differences between programs that run directly in the RealSense SDK (such as the RealSense Viewer) and a launch in the RealSense ROS wrapper (which is a layer that interacts closely with librealsense but handles some processes differently in order to have compatibility with ROS).

**Comment by ghost** [comment] 2021-10-13 15:03
Alright running that command resulted in the same output of repeated control_transfer warning along with no data in rviz. I can still echo and see data coming from the depth topic in the cli however.

**Comment by MartyG-RealSense** [comment] 2021-10-13 17:09
I recall a past case on L515 where the problem was apparently that Infra was disabled.  So is there any change in RViz2 if infra is enabled?

**ros2 launch realsense2_camera rs_launch.py enable_infra:=true**

**Comment by ghost** [comment] 2021-10-13 18:58
I am still unable to view the image in rviz2 or the point cloud. The weird thing is, I can subscribe to the color and depth topics and view the image using this opencv node that I made, so the data is definitely getting through, it almost seems like this is an rviz2 bug at this point
[viewer.txt](https://github.com/IntelRealSense/realsense-ros/files/7340677/viewer.txt)
.
it is a cpp file, for some reason dropping my code in code format wasnt working

**Comment by MartyG-RealSense** [comment] 2021-10-14 09:04
Going back to when you tried **demo_pointcloud_launch_py**, did you set Fixed Frame to **camera_link** in RViz2 as indicated in the tutorial for that launch in the link below, please? 

https://github.com/IntelRealSense/realsense-ros/tree/ros2#point-cloud

![image](https://user-images.githubusercontent.com/41145062/137286243-f0098835-f798-49f7-a141-5797a15b05e5.png)

**Comment by ghost** [comment] 2021-10-14 13:09
Yep I have double checked the fixed frame. I also tried double checking all of the QoS with no luck. The data is still being published to the topic, however it is still not visible in Rviz.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/65035135/137323364-e7387d0b-07b8-4106-9f4a-aca5f8c46173.png)

**Comment by MartyG-RealSense** [comment] 2021-10-14 15:49
And you have used the **Add** button to add the **/camera/color/image_raw** topic, please?

**Comment by ghost** [comment] 2021-10-15 01:28
I have with both the "launch_demo_pointcloud" and "rs_launch" and many combinations of the parameter options.

**Comment by MartyG-RealSense** [comment] 2021-10-15 11:17
Which methods did you use to install the librealsense SDK and the RealSense ROS wrapper, please?

**Comment by ghost** [comment] 2021-10-15 14:50
I installed librealsense via the apt package manager and I have tried the the foxy and ros2 branches of the realsense ros-wrapper from source and the foxy package from the apt package manager. My currently installed packages are the two packages installed through apt.

**Comment by ghost** [comment] 2021-10-15 14:51
I have also checked the QoS on the published topics and the QoS setup in Rviz. I have tried matching them exactly and the other combinations just in case.

**Comment by MartyG-RealSense** [comment] 2021-10-15 16:27
If librealsense is installed on its own from packages then the RealSense ROS2 wrapper should subsequently be installed from source code using **Method 2** in the ROS wrapper installation documentation  The librealsense SDK should be installed first and then the ROS wrapper installed secondly afterwards.

If librealsense was installed on its own from packages then ROS wrapper installation **Method 1** should not be used.  This is because this method installs both librealsense and the ROS wrapper together from packages.  So if you installed librealsense on its own first and then used Method 2, you would be installing librealsense twice.

If you do not have an Nvidia graphics chip in your computer and therefore do not need CUDA graphics acceleration support (which only works with Nvidia graphics hardware) then the simplest approach may be to install ROS Foxy from Debian packages and then install librealsense and the ROS wrapper together from packages using Method 1.

**Comment by ghost** [comment] 2021-10-15 17:26
Interesting. Since they were all installed from the debian packages though, wouldnt it have recognized that librealsense was already manually installed and skipped? And I am working with an Nvidia card for graphics acceleration, although I do think it is directly with the realsense (or at least not on purpose). That is being utilized to run a Pytorch DNN.

**Comment by ghost** [comment] 2021-10-15 18:19
If it was just the installs of librealsense and the ros-wrapper however, why wouldn't it affect the ability to get the image from the camera and post it to a topic rather than the ability of Rviz to display the topic?

**Comment by ghost** [comment] 2021-10-15 21:09
I would like to give an update. I believe the issue did not stem from the Real sense library. I believe there was some sort of issue with the rviz2 installation. I have tried the camera on a different machine and although the errors are still firing away with almost every frame, I have successfully been able to get all of the feeds and even the pointcloud to show up in Rviz2 on the other machine. I think this issue can be closed unless you have anything further to add.

**Comment by MartyG-RealSense** [comment] 2021-10-16 09:14
I do not have anything further to add.  Thanks very much @seandburke99 for the update of your progress!  As suggested, I will close the issue. Thanks again   :)

**Closed as completed by MartyG-RealSense** 2021-10-16 09:14 UTC
Labels: l500
