### ISSUE TITLE
Why is there always a difference of 4mm between the depth of the same object in the morning and in the afternoon ?

### ISSUE THREAD

**Issue by AtariaLee** [realsenseai/realsense-ros#2342] opened 2022-05-07 07:58 UTC
Measurements of the depth of the same object in the morning and afternoon will always be off by about 4mm under almost identical lighting conditions.  I mean the difference between the average depth in the morning and the average depth in the afternoon is 4 mm. Whether it is cloudy or sunny, the depth of each time period is similar.  But the difference between morning and afternoon is always four millimeters .What causes this situation?

 Camera Model :                                   D435I
 Firmware Version:                                05.12.15.50
 Operating System & Version:              ubuntu18.04                                
 Platform :                                             PC  
 SDK Version :                                       2.48.0                     
 Language :                                           C++、opencv                          
 Segment	:		                             Robot                          

Depth measured at noon（938mm）:
![下午938](https://user-images.githubusercontent.com/82266183/167243794-14ff8027-9f57-4e82-8e9e-cf6754879c2d.png)

Depth values measured in the morning(942mm):
![11111](https://user-images.githubusercontent.com/82266183/167243966-cf76d507-8c8a-4869-864e-efc4708d79b9.png)

**Comment by MartyG-RealSense** [comment] 2022-05-07 13:38
Closed as a duplicate of https://github.com/IntelRealSense/librealsense/issues/10476

**Closed as completed by MartyG-RealSense** 2022-05-07 13:38 UTC
