### ISSUE TITLE
Why the translation results of y and z axis between IMU and camera are reverse with RealSenseD435i?

### ISSUE THREAD

**Issue by opendvd** [realsenseai/realsense-ros#1527] opened 2020-11-27 12:48 UTC
I use Kailbr to calibrate the RealSenseD435i, especially the external parameters between IMU and camera. But the external parameters of translation between IMU and camera confused me. The Kalibr's results are different with ideal value.
The ideal value is:
t_IC0 = [-0.006 0.005 0.012]T;
t_IC1 = [0.044 0.005 0.012]T;
But kalibr result is:
t_IC0 = [-0.00510796 0.01859231 0.00576145]T;
t_IC1 = [0.04383316 0.01886102 0.00574488]T;
So why the results of y and z axis are reverse?
Kalibr's result is here: 
[results-imucam-imu_cameras_calibration.txt](https://github.com/IntelRealSense/realsense-ros/files/5607894/results-imucam-imu_cameras_calibration.txt)

**Comment by MartyG-RealSense** [comment] 2020-11-27 13:41
Closed as duplicate of https://github.com/IntelRealSense/librealsense/issues/7865

**Closed as completed** 2020-11-27 13:48 UTC
