### ISSUE TITLE
Problems with topics /camera/aligned_depth_to_infra1/*

### ISSUE THREAD

**Issue by IzzyCoder** [realsenseai/realsense-ros#2407] opened 2022-07-11 11:21 UTC
Hello,
I'm using RealSense D435I camera on Ubuntu 20.04 with ROS Galactic.
I'm running the the camera node with following command line:
`ros2 launch realsense2_camera rs_launch.py align_depth.enable:=true enable_depth:=true enable_infra1:=true enable_infra2:=true`
The topic list is:
```
/camera/aligned_depth_to_color/camera_info
/camera/aligned_depth_to_color/image_raw
/camera/aligned_depth_to_color/image_raw/compressed
/camera/aligned_depth_to_color/image_raw/compressedDepth
/camera/aligned_depth_to_infra1/camera_info
/camera/aligned_depth_to_infra1/image_raw
/camera/aligned_depth_to_infra1/image_raw/compressed
/camera/aligned_depth_to_infra1/image_raw/compressedDepth
/camera/color/camera_info
/camera/color/image_raw
/camera/color/image_raw/compressed
/camera/color/image_raw/compressedDepth
/camera/color/metadata
/camera/depth/camera_info
/camera/depth/image_rect_raw
/camera/depth/image_rect_raw/compressed
/camera/depth/image_rect_raw/compressedDepth
/camera/depth/metadata
/camera/extrinsics/depth_to_color
/camera/extrinsics/depth_to_infra1
/camera/extrinsics/depth_to_infra2
/camera/imu
/camera/infra1/camera_info
/camera/infra1/image_rect_raw
/camera/infra1/image_rect_raw/compressed
/camera/infra1/image_rect_raw/compressedDepth
/camera/infra1/metadata
/camera/infra2/camera_info
/camera/infra2/image_rect_raw
/camera/infra2/image_rect_raw/compressed
/camera/infra2/image_rect_raw/compressedDepth
/camera/infra2/metadata
/parameter_events
/rosout
/tf_static

```
I'm interested in `/camera/aligned_depth_to_infra1/*` topics, however there seem to be no messages published on those topics - ros2 topic hz/echo commands give nothing. Topics `/camera/aligned_depth_to_color/*` ,on the other hand, work just fine.

Am I missing something?
Thanks in advance.

**Comment by MartyG-RealSense** [comment] 2022-07-11 12:26
Hi @IzzyCoder  There is one previous past case of this issue at https://github.com/IntelRealSense/realsense-ros/issues/1060 regarding no messages being published for the **/camera/aligned_depth_to_infra1** topic when align_depth is true.  It was thought that the cause of the problem might be the kernel version that was being used.  Which kernel version do you have, please?

**Comment by IzzyCoder** [comment] 2022-07-11 14:26
> Hi @IzzyCoder There is one previous past case of this issue at #1060 regarding no messages being published for the **/camera/aligned_depth_to_infra1** topic when align_depth is true. It was thought that the cause of the problem might be the kernel version that was being used. Which kernel version do you have, please?

Hi,
My kernel version is `5.13.0-52-generic`.

**Comment by MartyG-RealSense** [comment] 2022-07-11 14:33
The current 2.50.0 version of the librealsense SDK does not have built-in support for kernel 5.13, with the newest supported kernel series being 5.11.  Whilst the SDK can work with unsupported kernels, there may be unpredictable consequences in regards to stability.

A draft kernel patch that adds support for 5.13 and 5.15 kernels was recently provided at https://github.com/IntelRealSense/librealsense/issues/10439#issuecomment-1171965106

Alternatively, you could try building the SDK from source code with the **RSUSB backend** installation method if you are not doing so already, as this install method bypasses the kernel and so the RSUSB build is not dependent on Linux versions or kernel versions and does not require patching.

**Comment by IzzyCoder** [comment] 2022-07-11 14:38
Thanks for your help!

**Comment by MartyG-RealSense** [comment] 2022-07-18 06:36
Hi @IzzyCoder  Do you require further assistance with this case, please?  Thanks!

**Comment by IzzyCoder** [comment] 2022-07-19 10:46
Hi @MartyG-RealSense 
I’ve ran recently into the same issue on Jetson NX, I’m assuming for the same reasons.
Other than that, no, thank you.

**Comment by MartyG-RealSense** [comment] 2022-07-19 11:40
Thanks very much for the update.  Have you tried the methods suggested in https://github.com/IntelRealSense/realsense-ros/issues/2407#issuecomment-1180487683 please (using kernel 5.11, applying the draft kernel patch or using an RSUSB source code build of librealsense)

**Comment by IzzyCoder** [comment] 2022-07-20 12:32
> 

Hi,

No, I haven't tried using another version of Kernel. However, it does seem that the default depth topic `/camera/depth/*` is aligned with the left IR sensor (verified by visually aligning the images). Also, the transform published on `/camera/extrinsics/depth_to_infra1` topic is an identity transform. So for now I'm going to try using this topic as aligned.

**Comment by MartyG-RealSense** [comment] 2022-07-20 13:34
Thanks @IzzyCoder - please do let me know if you require further assistance.  :)

**Comment by IzzyCoder** [comment] 2022-07-20 14:11
Thanks, @MartyG-RealSense .

**Comment by MartyG-RealSense** [comment] 2022-07-26 10:04
Hi @IzzyCoder  Do you require further assistance with this case, please?  Thanks!

**Comment by IzzyCoder** [comment] 2022-07-26 10:56
@MartyG-RealSense, not for now, thanks!

**Comment by MartyG-RealSense** [comment] 2022-07-26 11:35
Thanks very much @IzzyCoder for the update!  As you do not require further asssistance at this time, I will close this case.  Thanks again!

**Closed as completed by MartyG-RealSense** 2022-07-26 11:35 UTC
Labels: D400
