### ISSUE TITLE
src/base_realsense_node.cpp:643:56: error: ‘class rs2::processing_block’ has no member named ‘process’                          frameset = filter_it->_filter->process(frameset);

### ISSUE THREAD

**Issue by lucasjinreal** [realsenseai/realsense-ros#524] opened 2018-11-30 09:52 UTC
So many build errors

**Comment by L4ncelot** [comment] 2018-11-30 14:39
Having now the same issue. This repo worked for me until today after I updated system with `apt update` and `apt upgrade`...

It did work fine with realsense2 library version `2.16.5`. Now it doesn't work with the new version `2.17.0`.

**Comment by opalmirror** [comment] 2018-11-30 20:22
This issue is a duplicate of #522

**Comment by doronhi** [comment] 2018-12-06 05:11
Release of v2.1.2 merged PR#523 by @m-price-softwearinc  to comply with librealsense v2.17.0 and fix this problem.

**Closed as completed by doronhi** 2018-12-06 05:11 UTC
