### ISSUE TITLE
why pointcloud data set to (0,0,0) if z>5.0f?

### ISSUE THREAD

**Issue by ahuizxc** [realsenseai/realsense-ros#493] opened 2018-10-16 02:18 UTC
cannot understand why set this threshold, it can cause bad influence while displaying the pointcloud data in rviz.
thanks :)
code on branch 2.0.1 line912-917

                    if (depth_point[2] <= 0.f || depth_point[2] > 5.f)
                    {
                        depth_point[0] = 0.f;
                        depth_point[1] = 0.f;
                        depth_point[2] = 0.f;
                    }

**Comment by doronhi** [comment] 2018-10-25 11:59
We no longer use the specified piece of code if I close it as irrelevant.

**Closed as completed by doronhi** 2018-10-25 11:59 UTC

**Comment by ahuizxc** [comment] 2018-10-26 01:05
We need this topic that subscribed by rviz, and the pointcloud displayed in rviz is very terrible!

**Comment by doronhi** [comment] 2018-10-26 02:48
What version of realsense2_camera are you using? The latest version use the pointcloud function from librealsense so if you can. A first good step would be to update both.
As for bad looking pointcloud, it means poor depth performance and could be caused by several factors. I would start by checking out this paper:
https://www.intel.com/content/dam/support/us/en/documents/emerging-technologies/intel-realsense-technology/BKMs_Tuning_RealSense_D4xx_Cam.pdf

**Comment by freemanlo** [comment] 2018-10-26 02:54
Hi @ahuizxc,

1. What's your required use range? 
2. You can consider to change the preset (ex: high density for depth) to see how it works.
3. You can also increase the laser projector power if a long distance is required.
