### ISSUE TITLE
without rs_l515/accel/sample and rs_l515/gyro/sample

### ISSUE THREAD

**Issue by qetuo105487900** [realsenseai/realsense-ros#3031] opened 2024-03-01 12:27 UTC
without accel/sample and gyro/sample 

what happened ?

lun@lun:~$ rostopic list
/diagnostics
/rosout
/rosout_agg
/rs_d435i/align_to_color/parameter_descriptions
/rs_d435i/align_to_color/parameter_updates
/rs_d435i/aligned_depth_to_color/camera_info
/rs_d435i/aligned_depth_to_color/image_raw
/rs_d435i/aligned_depth_to_color/image_raw/compressed
/rs_d435i/aligned_depth_to_color/image_raw/compressed/parameter_descriptions
/rs_d435i/aligned_depth_to_color/image_raw/compressed/parameter_updates
/rs_d435i/aligned_depth_to_color/image_raw/compressedDepth
/rs_d435i/aligned_depth_to_color/image_raw/compressedDepth/parameter_descriptions
/rs_d435i/aligned_depth_to_color/image_raw/compressedDepth/parameter_updates
/rs_d435i/aligned_depth_to_color/image_raw/theora
/rs_d435i/aligned_depth_to_color/image_raw/theora/parameter_descriptions
/rs_d435i/aligned_depth_to_color/image_raw/theora/parameter_updates
/rs_d435i/color/camera_info
/rs_d435i/color/image_raw
/rs_d435i/color/image_raw/compressed
/rs_d435i/color/image_raw/compressed/parameter_descriptions
/rs_d435i/color/image_raw/compressed/parameter_updates
/rs_d435i/color/image_raw/compressedDepth
/rs_d435i/color/image_raw/compressedDepth/parameter_descriptions
/rs_d435i/color/image_raw/compressedDepth/parameter_updates
/rs_d435i/color/image_raw/theora
/rs_d435i/color/image_raw/theora/parameter_descriptions
/rs_d435i/color/image_raw/theora/parameter_updates
/rs_d435i/color/metadata
/rs_d435i/depth/camera_info
/rs_d435i/depth/image_rect_raw
/rs_d435i/depth/image_rect_raw/compressed
/rs_d435i/depth/image_rect_raw/compressed/parameter_descriptions
/rs_d435i/depth/image_rect_raw/compressed/parameter_updates
/rs_d435i/depth/image_rect_raw/compressedDepth
/rs_d435i/depth/image_rect_raw/compressedDepth/parameter_descriptions
/rs_d435i/depth/image_rect_raw/compressedDepth/parameter_updates
/rs_d435i/depth/image_rect_raw/theora
/rs_d435i/depth/image_rect_raw/theora/parameter_descriptions
/rs_d435i/depth/image_rect_raw/theora/parameter_updates
/rs_d435i/depth/metadata
/rs_d435i/extrinsics/depth_to_color
/rs_d435i/motion_module/parameter_descriptions
/rs_d435i/motion_module/parameter_updates
/rs_d435i/realsense2_camera_manager/bond
/rs_d435i/rgb_camera/auto_exposure_roi/parameter_descriptions
/rs_d435i/rgb_camera/auto_exposure_roi/parameter_updates
/rs_d435i/rgb_camera/parameter_descriptions
/rs_d435i/rgb_camera/parameter_updates
/rs_d435i/stereo_module/auto_exposure_roi/parameter_descriptions
/rs_d435i/stereo_module/auto_exposure_roi/parameter_updates
/rs_d435i/stereo_module/parameter_descriptions
/rs_d435i/stereo_module/parameter_updates
/rs_l515/accel/imu_info
/rs_l515/align_to_color/parameter_descriptions
/rs_l515/align_to_color/parameter_updates
/rs_l515/aligned_depth_to_color/camera_info
/rs_l515/aligned_depth_to_color/image_raw
/rs_l515/aligned_depth_to_color/image_raw/compressed
/rs_l515/aligned_depth_to_color/image_raw/compressed/parameter_descriptions
/rs_l515/aligned_depth_to_color/image_raw/compressed/parameter_updates
/rs_l515/aligned_depth_to_color/image_raw/compressedDepth
/rs_l515/aligned_depth_to_color/image_raw/compressedDepth/parameter_descriptions
/rs_l515/aligned_depth_to_color/image_raw/compressedDepth/parameter_updates
/rs_l515/aligned_depth_to_color/image_raw/theora
/rs_l515/aligned_depth_to_color/image_raw/theora/parameter_descriptions
/rs_l515/aligned_depth_to_color/image_raw/theora/parameter_updates
/rs_l515/color/camera_info
/rs_l515/color/image_raw
/rs_l515/color/image_raw/compressed
/rs_l515/color/image_raw/compressed/parameter_descriptions
/rs_l515/color/image_raw/compressed/parameter_updates
/rs_l515/color/image_raw/compressedDepth
/rs_l515/color/image_raw/compressedDepth/parameter_descriptions
/rs_l515/color/image_raw/compressedDepth/parameter_updates
/rs_l515/color/image_raw/theora
/rs_l515/color/image_raw/theora/parameter_descriptions
/rs_l515/color/image_raw/theora/parameter_updates
/rs_l515/color/metadata
/rs_l515/depth/camera_info
/rs_l515/depth/image_rect_raw
/rs_l515/depth/image_rect_raw/compressed
/rs_l515/depth/image_rect_raw/compressed/parameter_descriptions
/rs_l515/depth/image_rect_raw/compressed/parameter_updates
/rs_l515/depth/image_rect_raw/compressedDepth
/rs_l515/depth/image_rect_raw/compressedDepth/parameter_descriptions
/rs_l515/depth/image_rect_raw/compressedDepth/parameter_updates
/rs_l515/depth/image_rect_raw/theora
/rs_l515/depth/image_rect_raw/theora/parameter_descriptions
/rs_l515/depth/image_rect_raw/theora/parameter_updates
/rs_l515/depth/metadata
/rs_l515/extrinsics/depth_to_color
/rs_l515/gyro/imu_info
/rs_l515/imu
/rs_l515/l500_depth_sensor/parameter_descriptions
/rs_l515/l500_depth_sensor/parameter_updates
/rs_l515/motion_module/parameter_descriptions
/rs_l515/motion_module/parameter_updates
/rs_l515/realsense2_camera_manager/bond
/rs_l515/rgb_camera/parameter_descriptions
/rs_l515/rgb_camera/parameter_updates
/tf
/tf_static

**Comment by MartyG-RealSense** [comment] 2024-03-01 15:33
Closed as duplicate of https://github.com/IntelRealSense/librealsense/issues/12718

**Closed as completed by MartyG-RealSense** 2024-03-01 15:33 UTC
