### ISSUE TITLE
Cannot build realsense-ros pkg saying avandoned because it `depends on unknown jobs: librealsense2`

### ISSUE THREAD

**Issue by Karin-Sugi** [realsenseai/realsense-ros#2782] opened 2023-06-17 12:26 UTC
Hi, I am trying to use realsenese with RaspberryPi 4. Now, I've cloned librealsense and built it. Thus, as a next step, I cloned realsense-ros package and tried to built it. However, it is avandoned saying the packages is `depends on unknown jobs: librealsense2`.

What I did for install is following.

```
// install librealsense
$ git clone https://github.com/IntelRealSense/librealsense.git
$ cd librealsense/
$ sudo apt install -y git libssl-dev libusb-1.0-0-dev pkg-config libgtk-3-dev
$ sudo apt install -y libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev
$ sudo apt install -y cmake
$ ./scripts/setup_udev_rules.sh
$ ./scripts/patch-realsense-ubuntu-lts.sh
$ mkdir build && cd build
$ cmake ../ -DFORCE_RSUSB_BACKEND=true -DCMAKE_BUILD_TYPE=release -DBUILD_EXAMPLES=true -DBUILD_GRAPHICAL_EXAMPLES=true
$ sudo make clean && make && sudo make install

// install realsense-ros package
$ cd ~/hauser_ws/src
$ sudo apt install ros-melodic-ddynamic-reconfigure
$ git clone https://github.com/IntelRealSense/realsense-ros.git
$ cd realsense-ros/
$ git checkout `git tag | sort -V | grep -P "^2.\d+\.\d+" | tail -1`
$ cd ../../
$ catkin init
$ catkin clean
$ catkin config --cmake-args -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release
$ catkin build
```
I am sure my realsense viewer works fine.
How can I fix it?

Thanks in advance,
Karin

**Comment by MartyG-RealSense** [comment] 2023-06-17 16:04
Closed as a duplicate of https://github.com/IntelRealSense/librealsense/issues/11919

**Closed as completed by MartyG-RealSense** 2023-06-17 16:04 UTC
